export const THREAT_CATEGORIES = [
  { value: "wildlife", label: "Wildlife", icon: "🦁" },
  { value: "poaching", label: "Poaching", icon: "🚫" },
  { value: "habitat_destruction", label: "Habitat Destruction", icon: "🏚️" },
  { value: "wildlife_sighting", label: "Wildlife Sighting", icon: "👁️" },
  { value: "human_wildlife_conflict", label: "Human-Wildlife Conflict", icon: "⚠️" },
  { value: "pollution", label: "Pollution", icon: "☣️" },
  { value: "invasive_species", label: "Invasive Species", icon: "🦠" },
  { value: "illegal_logging", label: "Illegal Logging", icon: "🪓" },
  { value: "fire", label: "Fire", icon: "🔥" },
  { value: "disease_outbreak", label: "Disease Outbreak", icon: "🦠" },
  { value: "illegal_mining", label: "Illegal Mining", icon: "⛏️" },
  { value: "deforestation", label: "Deforestation", icon: "🌲" },
  { value: "water_pollution", label: "Water Pollution", icon: "💧" },
  { value: "air_pollution", label: "Air Pollution", icon: "💨" },
  { value: "soil_erosion", label: "Soil Erosion", icon: "🏔️" },
  { value: "climate_impact", label: "Climate Impact", icon: "🌡️" },
  { value: "endangered_species", label: "Endangered Species", icon: "🐾" },
  { value: "conservation_success", label: "Conservation Success", icon: "✅" },
  { value: "other", label: "Other (please specify)", icon: "📝" }
]; 